/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BibleHubAutoLinkerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/linker.ts
var BOOKS = [
  { canonical: "Genesis", slug: "genesis", aliases: ["Gen"] },
  { canonical: "Exodus", slug: "exodus", aliases: ["Exod", "Ex"] },
  { canonical: "Leviticus", slug: "leviticus", aliases: ["Lev"] },
  { canonical: "Numbers", slug: "numbers", aliases: ["Num"] },
  { canonical: "Deuteronomy", slug: "deuteronomy", aliases: ["Deut"] },
  { canonical: "Joshua", slug: "joshua", aliases: ["Josh"] },
  { canonical: "Judges", slug: "judges", aliases: ["Judg"] },
  { canonical: "Ruth", slug: "ruth", aliases: [] },
  { canonical: "1 Samuel", slug: "1_samuel", aliases: ["1 Sam"] },
  { canonical: "2 Samuel", slug: "2_samuel", aliases: ["2 Sam"] },
  { canonical: "1 Kings", slug: "1_kings", aliases: [] },
  { canonical: "2 Kings", slug: "2_kings", aliases: [] },
  { canonical: "1 Chronicles", slug: "1_chronicles", aliases: ["1 Chron"] },
  { canonical: "2 Chronicles", slug: "2_chronicles", aliases: ["2 Chron"] },
  { canonical: "Ezra", slug: "ezra", aliases: [] },
  { canonical: "Nehemiah", slug: "nehemiah", aliases: ["Neh"] },
  { canonical: "Esther", slug: "esther", aliases: ["Esth"] },
  { canonical: "Job", slug: "job", aliases: [] },
  { canonical: "Psalms", slug: "psalms", aliases: ["Psalm", "Ps", "Psa"] },
  { canonical: "Proverbs", slug: "proverbs", aliases: ["Prov"] },
  { canonical: "Ecclesiastes", slug: "ecclesiastes", aliases: ["Eccl"] },
  { canonical: "Song of Solomon", slug: "songs", aliases: ["Song", "Song of Songs"] },
  { canonical: "Isaiah", slug: "isaiah", aliases: ["Isa"] },
  { canonical: "Jeremiah", slug: "jeremiah", aliases: ["Jer"] },
  { canonical: "Lamentations", slug: "lamentations", aliases: ["Lam"] },
  { canonical: "Ezekiel", slug: "ezekiel", aliases: ["Ezek"] },
  { canonical: "Daniel", slug: "daniel", aliases: ["Dan"] },
  { canonical: "Hosea", slug: "hosea", aliases: ["Hos"] },
  { canonical: "Joel", slug: "joel", aliases: [] },
  { canonical: "Amos", slug: "amos", aliases: [] },
  { canonical: "Obadiah", slug: "obadiah", aliases: ["Obad"] },
  { canonical: "Jonah", slug: "jonah", aliases: [] },
  { canonical: "Micah", slug: "micah", aliases: ["Mic"] },
  { canonical: "Nahum", slug: "nahum", aliases: ["Nah"] },
  { canonical: "Habakkuk", slug: "habakkuk", aliases: ["Hab"] },
  { canonical: "Zephaniah", slug: "zephaniah", aliases: ["Zeph"] },
  { canonical: "Haggai", slug: "haggai", aliases: ["Hag"] },
  { canonical: "Zechariah", slug: "zechariah", aliases: ["Zech"] },
  { canonical: "Malachi", slug: "malachi", aliases: ["Mal"] },
  { canonical: "Matthew", slug: "matthew", aliases: ["Matt", "Mt"] },
  { canonical: "Mark", slug: "mark", aliases: ["Mk"] },
  { canonical: "Luke", slug: "luke", aliases: ["Lk"] },
  { canonical: "John", slug: "john", aliases: ["Jn"] },
  { canonical: "Acts", slug: "acts", aliases: [] },
  { canonical: "Romans", slug: "romans", aliases: ["Rom"] },
  { canonical: "1 Corinthians", slug: "1_corinthians", aliases: ["1 Cor"] },
  { canonical: "2 Corinthians", slug: "2_corinthians", aliases: ["2 Cor"] },
  { canonical: "Galatians", slug: "galatians", aliases: ["Gal"] },
  { canonical: "Ephesians", slug: "ephesians", aliases: ["Eph"] },
  { canonical: "Philippians", slug: "philippians", aliases: ["Phil"] },
  { canonical: "Colossians", slug: "colossians", aliases: ["Col"] },
  { canonical: "1 Thessalonians", slug: "1_thessalonians", aliases: ["1 Thess"] },
  { canonical: "2 Thessalonians", slug: "2_thessalonians", aliases: ["2 Thess"] },
  { canonical: "1 Timothy", slug: "1_timothy", aliases: ["1 Tim"] },
  { canonical: "2 Timothy", slug: "2_timothy", aliases: ["2 Tim"] },
  { canonical: "Titus", slug: "titus", aliases: [] },
  { canonical: "Philemon", slug: "philemon", aliases: ["Philem"] },
  { canonical: "Hebrews", slug: "hebrews", aliases: ["Heb"] },
  { canonical: "James", slug: "james", aliases: ["Jas"] },
  { canonical: "1 Peter", slug: "1_peter", aliases: ["1 Pet"] },
  { canonical: "2 Peter", slug: "2_peter", aliases: ["2 Pet"] },
  { canonical: "1 John", slug: "1_john", aliases: [] },
  { canonical: "2 John", slug: "2_john", aliases: [] },
  { canonical: "3 John", slug: "3_john", aliases: [] },
  { canonical: "Jude", slug: "jude", aliases: [] },
  { canonical: "Revelation", slug: "revelation", aliases: ["Rev"] }
];
var DEFAULT_SETTINGS = {
  enableAutoLink: true,
  linkProvider: "BibleHub",
  openInNewPane: false,
  convertRangesToFirstVerseUrl: true,
  enabledBooks: BOOKS.map((book) => book.canonical),
  enableAbbreviations: true,
  requireTriggerAfterReference: true
};
var NATURAL_DELIMITERS = /* @__PURE__ */ new Set([" ", "\n", "	", ".", ",", ";", ":", ")", "]", "}", "!", "?"]);
function buildBibleHubUrl(bookName, chapter, firstVerse) {
  const book = findBookByCanonical(bookName);
  if (!book) {
    throw new Error(`Unsupported Bible book: ${bookName}`);
  }
  return `https://biblehub.com/${book.slug}/${chapter}-${firstVerse}.htm`;
}
function convertBibleReferences(text, settings) {
  const matcher = createReferenceRegex(settings);
  const protectedRanges = collectProtectedRanges(text);
  let result = "";
  let lastIndex = 0;
  for (const match of text.matchAll(matcher)) {
    const reference = parseReferenceMatch(match, settings);
    if (!reference || isProtected(reference.from, reference.to, protectedRanges)) {
      continue;
    }
    result += text.slice(lastIndex, reference.from);
    result += createMarkdownLink(reference, settings);
    lastIndex = reference.to;
  }
  return result + text.slice(lastIndex);
}
function convertPastedText(text, settings) {
  if (!settings.enableAutoLink) {
    return text;
  }
  return convertBibleReferences(text, settings);
}
function convertReferenceAtOffset(text, offset, settings) {
  const matcher = createReferenceRegex(settings);
  const protectedRanges = collectProtectedRanges(text);
  for (const match of text.matchAll(matcher)) {
    const reference = parseReferenceMatch(match, settings);
    if (reference && offset >= reference.from && offset <= reference.to && !isProtected(reference.from, reference.to, protectedRanges)) {
      return {
        from: reference.from,
        to: reference.to,
        replacement: createMarkdownLink(reference, settings)
      };
    }
  }
  return null;
}
function isRangeProtectedInMarkdown(text, from, to) {
  return isProtected(from, to, collectProtectedRanges(text));
}
function convertTrailingReference(textBeforeCursor, settings) {
  if (!settings.enableAutoLink || textBeforeCursor.length === 0) {
    return null;
  }
  const delimiter = textBeforeCursor[textBeforeCursor.length - 1];
  if (settings.requireTriggerAfterReference && !NATURAL_DELIMITERS.has(delimiter)) {
    return null;
  }
  const searchText = settings.requireTriggerAfterReference ? textBeforeCursor.slice(0, -1) : textBeforeCursor;
  const matcher = createReferenceRegex(settings);
  const protectedRanges = collectProtectedRanges(textBeforeCursor);
  let trailing = null;
  for (const match of searchText.matchAll(matcher)) {
    const reference = parseReferenceMatch(match, settings);
    if (reference && reference.to === searchText.length) {
      trailing = reference;
    }
  }
  if (!trailing || isProtected(trailing.from, trailing.to, protectedRanges)) {
    return null;
  }
  return {
    from: trailing.from,
    to: trailing.to,
    replacement: createMarkdownLink(trailing, settings)
  };
}
function createMarkdownLink(reference, settings) {
  return `[${reference.text}](${buildBibleHubUrl(reference.canonical, reference.chapter, reference.firstVerse)})`;
}
function parseReferenceMatch(match, settings) {
  var _a, _b, _c;
  const fullMatch = match[0];
  const prefix = (_a = match[1]) != null ? _a : "";
  const bookText = match[2];
  const chapterText = match[3];
  const verseText = match[4];
  const from = ((_b = match.index) != null ? _b : 0) + prefix.length;
  const to = ((_c = match.index) != null ? _c : 0) + fullMatch.length;
  const book = findBookByAlias(bookText, settings);
  if (!book || !settings.enabledBooks.includes(book.canonical)) {
    return null;
  }
  return {
    from,
    to,
    text: fullMatch.slice(prefix.length),
    canonical: book.canonical,
    chapter: Number.parseInt(chapterText, 10),
    firstVerse: Number.parseInt(verseText, 10)
  };
}
function createReferenceRegex(settings) {
  const aliases = BOOKS.flatMap((book) => {
    const names = [book.canonical];
    if (settings.enableAbbreviations) {
      names.push(...book.aliases);
    }
    return names;
  }).sort((a, b) => b.length - a.length).map(aliasToPattern);
  return new RegExp(`(^|[^\\w/])(${aliases.join("|")})\\s+(\\d{1,3}):(\\d{1,3})(?:\\s*[-\u2013\u2014]\\s*\\d{1,3})?`, "gi");
}
function aliasToPattern(alias) {
  return escapeRegex(alias).replace(/\\ /g, "\\s+");
}
function findBookByCanonical(canonical) {
  return BOOKS.find((book) => book.canonical.toLowerCase() === canonical.toLowerCase());
}
function findBookByAlias(alias, settings) {
  const normalized = normalizeAlias(alias);
  return BOOKS.find((book) => {
    if (normalizeAlias(book.canonical) === normalized) {
      return true;
    }
    return settings.enableAbbreviations && book.aliases.some((candidate) => normalizeAlias(candidate) === normalized);
  });
}
function normalizeAlias(value) {
  return value.toLowerCase().replace(/\s+/g, " ").trim();
}
function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function collectProtectedRanges(text) {
  const ranges = [];
  addRegexRanges(text, /```[\s\S]*?```/g, ranges);
  addRegexRanges(text, /`[^`\n]*`/g, ranges);
  addRegexRanges(text, /\[[^\]\n]*\]\([^) \n]+(?:\s+"[^"]*")?\)/g, ranges);
  addRegexRanges(text, /https?:\/\/[^\s<>)]+/g, ranges);
  addOpenCodeRanges(text, ranges);
  return mergeRanges(ranges);
}
function addOpenCodeRanges(text, ranges) {
  const fenceMatches = Array.from(text.matchAll(/```/g));
  if (fenceMatches.length % 2 === 1) {
    const lastFence = fenceMatches[fenceMatches.length - 1];
    if (lastFence.index !== void 0) {
      ranges.push({ from: lastFence.index, to: text.length });
      return;
    }
  }
  const lastLineStart = text.lastIndexOf("\n") + 1;
  const lastLine = text.slice(lastLineStart);
  const backticks = Array.from(lastLine.matchAll(/`/g));
  if (backticks.length % 2 === 1) {
    const lastBacktick = backticks[backticks.length - 1];
    if (lastBacktick.index !== void 0) {
      ranges.push({ from: lastLineStart + lastBacktick.index, to: text.length });
    }
  }
}
function addRegexRanges(text, regex, ranges) {
  for (const match of text.matchAll(regex)) {
    if (match.index !== void 0) {
      ranges.push({ from: match.index, to: match.index + match[0].length });
    }
  }
}
function mergeRanges(ranges) {
  return ranges.sort((a, b) => a.from - b.from).reduce((merged, range) => {
    const previous = merged[merged.length - 1];
    if (!previous || range.from > previous.to) {
      merged.push({ ...range });
    } else {
      previous.to = Math.max(previous.to, range.to);
    }
    return merged;
  }, []);
}
function isProtected(from, to, ranges) {
  return ranges.some((range) => from < range.to && to > range.from);
}

// src/main.ts
var BibleHubAutoLinkerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.isApplyingChange = false;
  }
  async onload() {
    this.settings = { ...DEFAULT_SETTINGS, ...await this.loadData() };
    this.addSettingTab(new BibleHubAutoLinkerSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor) => {
        this.handleEditorChange(editor);
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        this.handleEditorMenu(menu, editor);
      })
    );
    this.registerDomEvent(document, "paste", (event) => {
      this.handlePaste(event);
    });
    this.addCommand({
      id: "convert-bible-references-current-note",
      name: "Convert Bible references in current note",
      editorCallback: (editor) => {
        const original = editor.getValue();
        const converted = convertBibleReferences(original, this.settings);
        if (converted !== original) {
          editor.setValue(converted);
          new import_obsidian.Notice("Converted Bible references to BibleHub links.");
        } else {
          new import_obsidian.Notice("No unlinked Bible references found.");
        }
      }
    });
    this.addCommand({
      id: "convert-selected-bible-references",
      name: "Convert selected Bible references",
      editorCallback: (editor) => {
        const selectedText = editor.getSelection();
        if (!selectedText) {
          new import_obsidian.Notice("Select Bible references to convert first.");
          return;
        }
        const converted = convertBibleReferences(selectedText, this.settings);
        if (converted !== selectedText) {
          editor.replaceSelection(converted);
          new import_obsidian.Notice("Converted selected Bible references.");
        } else {
          new import_obsidian.Notice("No unlinked Bible references found in selection.");
        }
      }
    });
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  handleEditorChange(editor) {
    if (this.isApplyingChange || !this.settings.enableAutoLink) {
      return;
    }
    const cursor = editor.getCursor();
    const textBeforeCursor = editor.getRange({ line: 0, ch: 0 }, cursor);
    const conversion = convertTrailingReference(textBeforeCursor, this.settings);
    if (!conversion) {
      return;
    }
    this.isApplyingChange = true;
    try {
      editor.replaceRange(
        conversion.replacement,
        editor.offsetToPos(conversion.from),
        editor.offsetToPos(conversion.to)
      );
    } finally {
      this.isApplyingChange = false;
    }
  }
  handleEditorMenu(menu, editor) {
    menu.addItem((item) => {
      item.setTitle("Link Bible reference").setIcon("link").onClick(() => {
        this.convertContextReference(editor);
      });
    });
  }
  convertContextReference(editor) {
    const selectedText = editor.getSelection();
    if (selectedText) {
      const converted = convertBibleReferences(selectedText, this.settings);
      if (converted !== selectedText) {
        editor.replaceSelection(converted);
      } else {
        new import_obsidian.Notice("No unlinked Bible reference found in selection.");
      }
      return;
    }
    const documentText = editor.getValue();
    const offset = editor.posToOffset(editor.getCursor());
    const conversion = convertReferenceAtOffset(documentText, offset, this.settings);
    if (!conversion) {
      new import_obsidian.Notice("No unlinked Bible reference found near the cursor.");
      return;
    }
    editor.replaceRange(
      conversion.replacement,
      editor.offsetToPos(conversion.from),
      editor.offsetToPos(conversion.to)
    );
  }
  handlePaste(event) {
    var _a;
    if (this.isApplyingChange || !this.settings.enableAutoLink) {
      return;
    }
    const pastedText = (_a = event.clipboardData) == null ? void 0 : _a.getData("text/plain");
    if (!pastedText) {
      return;
    }
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!markdownView) {
      return;
    }
    const editor = markdownView.editor;
    const pasteStart = editor.posToOffset(editor.getCursor("from"));
    const normalizedPaste = pastedText.replace(/\r\n?/g, "\n");
    window.setTimeout(() => {
      if (this.isApplyingChange) {
        return;
      }
      const pasteEnd = pasteStart + normalizedPaste.length;
      const documentText = editor.getValue();
      if (pasteEnd > documentText.length || isRangeProtectedInMarkdown(documentText, pasteStart, pasteEnd)) {
        return;
      }
      const from = editor.offsetToPos(pasteStart);
      const to = editor.offsetToPos(pasteEnd);
      const insertedText = editor.getRange(from, to);
      const converted = convertPastedText(insertedText, this.settings);
      if (converted === insertedText) {
        return;
      }
      this.isApplyingChange = true;
      try {
        editor.replaceRange(converted, from, to);
      } finally {
        this.isApplyingChange = false;
      }
    }, 0);
  }
};
var BibleHubAutoLinkerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "BibleHub Auto Linker" });
    new import_obsidian.Setting(containerEl).setName("Enable auto-link").setDesc("Convert references as you type after a natural delimiter.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableAutoLink).onChange(async (value) => {
        this.plugin.settings.enableAutoLink = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Link provider").setDesc("BibleHub is currently the only provider.").addText(
      (text) => text.setValue(this.plugin.settings.linkProvider).setDisabled(true)
    );
    new import_obsidian.Setting(containerEl).setName("Open in new pane").setDesc("Placeholder for future provider behavior.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.openInNewPane).onChange(async (value) => {
        this.plugin.settings.openInNewPane = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Use first verse URL for ranges").setDesc("BibleHub range references link to the first verse.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.convertRangesToFirstVerseUrl).onChange(async (value) => {
        this.plugin.settings.convertRangesToFirstVerseUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable abbreviations").setDesc("Recognize common abbreviations such as Jn, Rom, and 1 Cor.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableAbbreviations).onChange(async (value) => {
        this.plugin.settings.enableAbbreviations = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Require trigger after reference").setDesc("Only auto-link after a space, punctuation mark, newline, or similar delimiter.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.requireTriggerAfterReference).onChange(async (value) => {
        this.plugin.settings.requireTriggerAfterReference = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enabled books").setDesc("Comma-separated canonical book names. All 66 books are enabled by default.").addTextArea((text) => {
      text.inputEl.rows = 6;
      text.setValue(this.plugin.settings.enabledBooks.join(", ")).onChange(async (value) => {
        const requested = value.split(",").map((book) => book.trim()).filter(Boolean);
        const canonicalBooks = new Set(BOOKS.map((book) => book.canonical));
        this.plugin.settings.enabledBooks = requested.filter((book) => canonicalBooks.has(book));
        await this.plugin.saveSettings();
      });
    });
  }
};
